[instance]
problem_instance = "/fajsp/dafjs/DAFJS20" # configure problem instance to be scheduled

[algorithm]
scheduler_name = "random_scheduler" # heuristic rules: random_scheduler, greedy_scheduler, local_load_balancing_scheduler, global_load_balancing_scheduler

[output]
plotting = true # plot instance and gantt chart of generated schedule
 
