[instance]
problem_instance = "/fjsp_sdst/1_Fattahi/Fattahi_setup_15.fjs" # configure problem instance to be scheduled

[solver]
time_limit = 64800 # time limit for the gurobi solver, in seconds

[output]
plotting = true # draw ganttchart of found solution

